version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      -run:
        name: change to server
        command: "cd server"
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: npm run test