version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install-packages
          command: cd server && npm install
      - run:
          name: test
          command: cd server && npm run test