import LOGIN_VARIABLES from './login';
import REGISTER_VARIABLES from './register';
import DELETE_GOAL_VARIABLES from './deleteGoal';
import CREATE_GOAL_VARIABLES from './createGoal';
import UPDATE_GOAL_NAME_VARIABLES from './updateGoalName';
import UPDATE_GOAL_COMPLETED_VARIABLES from './updateGoalCompleted';
import CREATE_TASK_VARIABLES from './createTask';
import DELETE_TASK_VARIABLES from './deleteTask';
import UPDATE_TASK_NAME_VARIABLES from './updateTaskName';
import UPDATE_TASK_COMPLETED_VARIABLES from './updateTaskCompleted';
import CREATE_SUBTASK_VARIABLES from './createSubtask';
import DELETE_SUBTASK_VARIABLES from './deleteSubtask';
import START_SUBTASK_VARIABLES from './startSubtask';
import PAUSE_SUBTASK_VARIABLES from './pauseSubtask';
import COMPLETE_SUBTASK_VARIABLES from './completeSubtask';
import UPDATE_SUBTASK_VARIABLES from './updateSubtask';

export {
  LOGIN_VARIABLES,
  REGISTER_VARIABLES,
  DELETE_GOAL_VARIABLES,
  CREATE_GOAL_VARIABLES,
  UPDATE_GOAL_NAME_VARIABLES,
  UPDATE_GOAL_COMPLETED_VARIABLES,
  CREATE_TASK_VARIABLES,
  DELETE_TASK_VARIABLES,
  UPDATE_TASK_NAME_VARIABLES,
  UPDATE_TASK_COMPLETED_VARIABLES,
  CREATE_SUBTASK_VARIABLES,
  DELETE_SUBTASK_VARIABLES,
  START_SUBTASK_VARIABLES,
  PAUSE_SUBTASK_VARIABLES,
  COMPLETE_SUBTASK_VARIABLES,
  UPDATE_SUBTASK_VARIABLES,
};
