import LOGIN_VARIABLES from './login';
import REGISTER_VARIABLES from './register';
import DELETE_GOAL_VARIABLES from './deleteGoal';
import CREATE_GOAL_VARIABLES from './createGoal';
import UPDATE_GOAL_NAME_VARIABLES from './updateGoalName';
import UPDATE_GOAL_COMPLETED_VARIABLES from './updateGoalCompleted';
import CREATE_TASK_VARIABLES from './createTask';
import DELETE_TASK_VARIABLES from './deleteTask';
import UPDATE_TASK_NAME_VARIABLES from './updateTaskName';

export {
  LOGIN_VARIABLES,
  REGISTER_VARIABLES,
  DELETE_GOAL_VARIABLES,
  CREATE_GOAL_VARIABLES,
  UPDATE_GOAL_NAME_VARIABLES,
  UPDATE_GOAL_COMPLETED_VARIABLES,
  CREATE_TASK_VARIABLES,
  DELETE_TASK_VARIABLES,
  UPDATE_TASK_NAME_VARIABLES,
};
